---
apiVersion: v1
kind: Secret
metadata:
  name: w-secret
type: Opaque
data:
  username: cm9vdA==
  password: IVFBWjJ3c3g=
---
kind: Service
apiVersion: v1
metadata:
  name: w-ext-svc
spec:
  type: ExternalName
  externalName: flux-db.cfgr3xj38ihj.eu-central-1.rds.amazonaws.com
---
apiVersion: v1
kind: Service
metadata:
  name: w-svc
  labels:
    app: w-label
spec:
  ports:
  - port: 80
  selector:
    app: w-label
    tier: frontend
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: w-pvc
  labels:
    app: w-label
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: w-deploy
  labels:
    app: w-label
spec:
  selector:
    matchLabels:
      app: w-label
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: w-label
        tier: frontend
    spec:
      containers:
      - image: sadhanadockerhub0514/wp-image:82
        name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          value: w-ext-svc
        - name: WORDPRESS_DB_USER
          valueFrom:
            secretKeyRef:
              name: w-secret
              key: username
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: w-secret
              key: password
        ports:
        - containerPort: 80
          name: wordpress
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: w-pvc
